-- MySQL Script generated by MySQL Workbench
-- Fri Sep 25 13:44:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`individuo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`individuo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paciente` (
  `pacienteId` INT NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`pacienteId`),
  INDEX `fk_paciente_individuo1_idx` (`pacienteId` ASC) ,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) ,
  CONSTRAINT `fk_paciente_individuo1`
    FOREIGN KEY (`pacienteId`)
    REFERENCES `mydb`.`individuo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `whatsapp` VARCHAR(15) NOT NULL,
  `pacienteId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contato_paciente1_idx` (`pacienteId` ASC) ,
  CONSTRAINT `fk_contato_paciente1`
    FOREIGN KEY (`pacienteId`)
    REFERENCES `mydb`.`paciente` (`pacienteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(8) NOT NULL,
  `numero` INT NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `pacienteId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_endereco_paciente1_idx` (`pacienteId` ASC),
  CONSTRAINT `fk_endereco_paciente1`
    FOREIGN KEY (`pacienteId`)
    REFERENCES `mydb`.`paciente` (`pacienteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `usuario_id` INT NOT NULL,
  `categ` ENUM("profissional", "auxiliar", "administrador") NOT NULL,
  PRIMARY KEY (`usuario_id`),
  CONSTRAINT `fk_usuario_individuo1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`individuo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `usuarioId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_login_usuario1_idx` (`usuarioId` ASC) ,
  CONSTRAINT `fk_login_usuario1`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `mydb`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consulta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `concluida` TINYINT NOT NULL,
  `consultacol` VARCHAR(45) NOT NULL,
  `medicoId` INT NOT NULL,
  `pacienteId` INT NOT NULL,
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_consulta_usuario1_idx` (`medicoId` ASC) ,
  INDEX `fk_consulta_paciente1_idx` (`pacienteId` ASC) ,
  CONSTRAINT `fk_consulta_usuario1`
    FOREIGN KEY (`medicoId`)
    REFERENCES `mydb`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_paciente1`
    FOREIGN KEY (`pacienteId`)
    REFERENCES `mydb`.`paciente` (`pacienteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quitado` TINYINT NOT NULL,
  `resumo` TEXT(300) NULL,
  `valor` FLOAT NOT NULL,
  `consultaId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pagamento_consulta1_idx` (`consultaId` ASC) ,
  CONSTRAINT `fk_pagamento_consulta1`
    FOREIGN KEY (`consultaId`)
    REFERENCES `mydb`.`consulta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`relatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`relatorio` (
  `id` INT NOT NULL,
  `consultasConcluidas` INT NOT NULL,
  `consultasMarcadas` INT NOT NULL,
  `pagamentosPendentes` INT NOT NULL,
  `resumo` TEXT(400) NULL,
  `proxConsulta` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_relatorio_consulta1_idx` (`proxConsulta` ASC) ,
  CONSTRAINT `fk_relatorio_consulta1`
    FOREIGN KEY (`proxConsulta`)
    REFERENCES `mydb`.`consulta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
